algoritmo "IdadeparaPassar"
// Função : Solicita Idade e informa se pode continuar dirigindo
// Autor : Gabriela Silva Lopes
// Data : 14/06/2020
// Seção de Declarações 
var
idade: inteiro

inicio
//entrada
escreval("---COMEÇOU---")
escreval("Qual sua idade?")
leia(idade)
//processamento
se (idade>=18) entao
   escreval("Pode Passar!")
senao
   escreval("NÃO PODE PASSAR! Você é menor de idade.")
fimse

escreval("---ACABOU---")
fimalgoritmo
