algoritmo "areatriangulo"
// Função :  calcular area do triangulo
// Autor : gabriela silva lopes
// Data : 11/02/2020
// Seção de Declarações 
var
 b,h,r:real
inicio
// Seção de Comandos 
escreval("Digite o valor da base do triângulo em centímetros")
leia(b)
escreval("Digite o valor da altura do triângulo em centímetros")
leia(h)

//processamento
r<-(b*h)/2
//saída
escreval ("A área do triângulo é:",r)
fimalgoritmo
