algoritmo "areatriangulo"
// Função :   calcular a área de um triângulo
// Autor :  gabriela silva lopes
// Data : 11/02/2020
// Seção de Declarações 
var
b,h,r:real

inicio
// Seção de Comandos
escreval("Digite o valor da base do triângulo:")
leia(b)
escreval("Digite o valor da altura do triângulo")
leia(h)
//processamento
r<-(b*h)/2
//saída
escreval("O valor da área do triângulo é:",r)
fimalgoritmo
